### PR TITLE
Add Github action to generate release artifacts

### LINKED ISSUE #7: Builds
Release `1.0.0` does provide amd64 linux binary while newer releases don't. It would be good if the project had built binaries released with every version.

### PR DESCRIPTION
**Pull request by berendt**
Closes #7

Signed-off-by: Christian Berendt <berendt@osism.tech>

### CODE REVIEW

**Comment by berendt** [comment]
@greenpau Can you please take a look at it? We would like to include the OVN exporter in the Kolla project and that only works with release artefacts.

**Comment by berendt** [comment]
@greenpau Thanks. You now need to set a new tag on the repository so that the artifacts are built.

**Comment by greenpau** [comment]
@berendt , there is an error in github actions. Please see and let me know the next steps.

**Comment by berendt** [comment]
@greenpau Will fix this tomorrow.

**Comment by greenpau** [comment]
>  Will fix this tomorrow.

@berendt , please check if you can fix it.

**Pull request merged**
